### ISSUE TITLE
Problems building on macOS

### ISSUE THREAD

**Issue by njlr** [duneroadrunner/SaferCPlusPlus#2]
Hi there! 

I get this error trying to build the example on macOS: 

    In file included from msetl_example.cpp:45:
    In file included from ./mseregistered.h:12:
    ./msepointerbasics.h:380:117: error: no member named 'addressof' in namespace 'std'

Any ideas?

**Comment by duneroadrunner** [comment]
I'm afraid I don't have access to a mac. Which compiler are you using? Hmm, that's kind of a surprising error. I mean, std::addressof() is part of the standard library, right? http://en.cppreference.com/w/cpp/memory/addressof

**Comment by njlr** [comment]
I added `#include <memory>` to the top of `msepointerbasics.h`, which did the trick. 

However, this led to another issue: 

    msetl_example.cpp:389:43: error: copying variable of type 'mse::TXScopeObj<mse::msearray<int, 3> >' invokes deleted constructor
       mse::TXScopeObj<mse::msearray<int, 3>> array1_scpobj = mse::msearray<int, 3>{ 1, 2, 3 };
                                          ^               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ./msescope.h:294:12: note: 'TXScopeObj' has been explicitly marked deleted here
      explicit TXScopeObj(TXScopeObj&& _X) = delete;

**Comment by njlr** [comment]
I am using Clang BTW: 

    $ clang --version
    clang version 3.9.1 (tags/RELEASE_391/final)
    Target: x86_64-apple-darwin16.4.0
    Thread model: posix
    InstalledDir: /usr/local/bin

**Comment by duneroadrunner** [comment]
Sorry about that. I haven't yet incorporated the clang compiler into regular testing. That's long overdue. Ok, the latest works for me on clang 3.8 on ubuntu. Interestingly, the std::addressof() thing doesn't seem to be an issue on that setup. Lemme know if it works for you now. Thanks for the feedback.

**Comment by njlr** [comment]
Yes, that works now. Thanks! 

I implemented my build using [Buck](https://buckbuild.com/). The commit is [here](https://github.com/njlr/SaferCPlusPlus/commit/859787698c3d5ec4547426caf4fe8b1bbddab0d2). Buck build files can sit alongside other build systems without interference. Let me know if you want a PR.

**Comment by duneroadrunner** [comment]
Interesting, I'll have to look into Buck. For now though, I'm assuming the project is still small and simple enough to get away with not using a proper build system. :) Let me know if any other questions or comments come up. I know the documentation isn't that great yet.
