### ISSUE TITLE
Compiler directive to switch ?

### ISSUE THREAD

**Issue by harindu95** [duneroadrunner/SaferCPlusPlus#5]
In the documentation you have mentioned a compiler directive for switching to native counterparts. Is it implemented? And where can I find the docs for it?

Btw is there a reason for not overloading the std library directly? I would have preferred that.

**Comment by duneroadrunner** [comment]
To direct the library to use the native counterparts, you need to define MSE_SAFER_SUBSTITUTES_DISABLED, either as compiler option, as in

    -DMSE_SAFER_SUBSTITUTES_DISABLED

or by defining it in the source code before including the header files, as in

    #define MSE_SAFER_SUBSTITUTES_DISABLED
    #include "msemstdvector.h"

You can also switch individual elements to their native couterparts. If you look near the beginning of the [msetl_example.cpp](https://github.com/duneroadrunner/SaferCPlusPlus/blob/master/msetl_example.cpp) file, there are a bunch of commented out #define directives for doing just that. Also note that not all the elements have direct native counterparts.

Yeah, replacing the default standard library with a safe implementation would in many cases be ideal. But I don't know if there's a convenient way to just "override" elements in the standard library?

**Comment by harindu95** [comment]
Thanks for the quick reply. I think for now i will just stick to sanitizers. 
I think you can override standard library elements easily with a macro like this:
   #define std::shared_library safe::shared_library
