### ISSUE TITLE
Old style casts in msemsevector.h

### ISSUE THREAD

**Issue by 4144** [duneroadrunner/SaferCPlusPlus#6]
```
msemsevector.h:207:26: error: use of old-style cast [-Werror=old-style-cast]
```

Probably also in other files.
In C++ should be used safer cast versions like static_cast or const_cast or reinterpret_cast

**Comment by duneroadrunner** [comment]
Ok, I think I got'em all for you. :) Thanks.

**Comment by 4144** [comment]
Now look like fixed. thanks.
