### ISSUE TITLE
Use of std::type_info::hash_code() for type differentiation

### ISSUE THREAD

**Issue by djarek** [duneroadrunner/SaferCPlusPlus#9]
Use of std::type_info::hash_code() for type differentiation may result in UB if two types have the same value for hash_code() and code that relies on this fact performs an unsafe operation (e.g. call to a destructor of an object that does not exist within a tdp_variant).

https://github.com/duneroadrunner/SaferCPlusPlus/blob/d0bdd2d3f794511b6bc8aa2b169129c8409d24e8/msepoly.h#L103

**Comment by duneroadrunner** [comment]
Thanks. Replaced the hashes with `std::type_index`es. That should address the issue, right? It's not my area of expertise, but after a little reading, I don't know if it'd be an issue in practice. While cppreference.com does say that
> type_info objects referring to different types may have the same hash_code 

It also says that `std::type_info::hash_code()` is equivalent to `std::type_index::hash_code()`, which is equivalent to `std::hash<std::type_index>::operator()`. And `std::hash<>` has the requirement
> 5. For two different parameters k1 and k2 that are not equal, the probability that std::hash<Key>()(k1) == std::hash<Key>()(k2) should be very small, approaching 1.0/std::numeric_limits<size_t>::max()

Anyway, the variant implementation was provided before variant was available in the standard library. I think at some point it'll probably be dropped in favor of the standard library's version.

Let me know if you have any other questions or comments.

**Comment by djarek** [comment]
You're right that the likelihood of this occurring in a "normal" implementation of the stdlib is pretty low, but still, there was no need to rely on that. I believe it's correct now.
